$('document').ready(function(){
    $('.angle').click(function(){
       $('.section1').css({
           'display':'none'
       });
        $('.section2').css({
            'display':'block'
        });
    });
});